name: deploy-container
on: 
    push:
        branches:
            - master
        paths:
            - 'packages/container/**'

defaults:
    run:
        working-directory: packages/container

jobs:
    build: 
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run build
            - uses: jakejarvis/s3-sync-action@master
              with:
                args: --follow-symlinks --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
                SOURCE_DIR: 'packages/container/dist'      # optional: defaults to entire repository
                DEST_DIR: 'container/latest'
            
            - uses: ItsKarma/aws-cli@v1.70.0
              with:
                args: s3 ls s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: "eu-west-1"